### ISSUE TITLE
install problem?

### ISSUE THREAD

**Issue by xxl2005** [syllebra/bilbox-comfyui#8]
Traceback (most recent call last):
  File "/home/tobias/ComfyUI/nodes.py", line 1784, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tobias/ComfyUI/custom_nodes/bilbox-comfyui/__init__.py", line 2, in <module>
    from .bilbox_post_processing import BilboXLut, BilboXVignette
  File "/home/tobias/ComfyUI/custom_nodes/bilbox-comfyui/bilbox_post_processing.py", line 6, in <module>
    from colour.io.luts.iridas_cube import read_LUT_IridasCube, LUT3D, LUT3x1D
ModuleNotFoundError: No module named 'colour.io'; 'colour' is not a package

Cannot import /home/tobias/ComfyUI/custom_nodes/bilbox-comfyui module for custom nodes: No module named 'colour.io'; 'colour' is not a package

`tobias@pop-os:~$ pip install colour
Requirement already satisfied: colour in ./.local/lib/python3.10/site-packages (0.1.5)
tobias@pop-os:~$ `

colour is installed?

**Comment by AndyOne1** [comment]
You could try adding the colour module manually to your "ComfyUI/venv/Lib/site-packages" folder. I think there is also some mixup with another colour module. I uninstalled colour and colour-science and then reinstalled colour-science. That created a colour folder which I then manually copied to comfyUI's venv.

**Comment by syllebra** [comment]
Indeed, requirements are only installed automatically if you install the module from ComfyUI manager directly. I did not developped a mechanism to do it automatically from manual install.

**Comment by emourdavid** [comment]
You can use 
pip install colour colour-science
